### ISSUE TITLE
Firebase analytics integration does not work (out of the box)

### ISSUE THREAD

**Issue by ericntd** [mParticle/mparticle-android-sdk#68]
Hi mParticle,

the integration doesn't seem to work out of the box
(I verified it using [DebugView](https://firebase.google.com/docs/analytics/debugview#android))

What could the be the reasons?
Is it because of the naming convention?
Our events' look like "Subscription Purchased"
If yes, is there a way to bridge the name to satisfy Firebase Analytics's requirements?

Versions:
```
def mparticle = [
        appsflyer: "com.mparticle:android-appsflyer-kit:5.16.6",
        leanplum : "com.mparticle:android-leanplum-kit:5.16.6",
        firebase : "com.mparticle:android-googleanalyticsfirebase-kit:5.16.6",
]
```

Logs when app starts (no error)
```
D/mParticle: Loading Kit Framework.
D/mParticle: GoogleAnalyticsFirebaseKit detected.
D/mParticle: AppsFlyerKit detected.
D/mParticle: LeanplumKit detected.
D/mParticle: Kit Framework loaded.
D/mParticle: Restoring previous Kit configuration.
I/mParticle: Clearing Data Plan
D/mParticle: Started new session
D/mParticle: Logged event - 
    Event name: App Launch
    type: Other
    customAttributes:
    method:direct
    user id:null
D/mParticle: Queuing Kit event while waiting for initial configuration.
D/mParticle: Initializing kit: Leanplum
D/mParticle: Initializing kit: AppsFlyer
D/mParticle: Replaying events after receiving first kit configuration.
D/mParticle: Kit initialization complete. Disabling event queueing.
D/mParticle: Successfully collected Google Play Store Advertising ID.
```
